deployment:
  tasks:
    - export DEPLOYPATH=/home/h420462/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R cart $DEPLOYPATH
    - /bin/cp -R checkout $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R payment $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
